import Footer from "@/components/Footer";
import Header from "@/components/Header";
import GlobalLoading from "@/components/GlobalLoading";
import "@/styles/globals.css";
import Head from "next/head";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { SessionProvider, useSession } from "next-auth/react";
import { StoreProvider } from "@/utils/Store";
import { useRouter } from "next/router";

export default function App({
  Component,
  pageProps: { session, ...pageProps },
}) {
  function Auth({ children, adminOnly }) {
    const router = useRouter();
    const { status, data: session } = useSession({
      required: true,
      onUnauthenticated() {
        router.push("/unauthorized?message=login required");
      },
    });
    if (status === "loading") {
      return <GlobalLoading />;
    }
    if (adminOnly && !session.user.isAdmin) {
      router.push("/unauthorized?message=Admin login required");
    }

    return children;
  }

  return (
    <SessionProvider session={session}>
      <StoreProvider>
        {Component.auth ? (
          <Auth adminOnly={Component.auth.adminOnly}>
            <Head>
              <title>Shoe Store</title>
              <meta name="description" content="Generated by create next app" />
              <meta
                name="viewport"
                content="width=device-width, initial-scale=1"
              />
              <link rel="icon" href="/favicon.ico" />
              <link rel="preconnect" href="https://fonts.googleapis.com" />
              <link
                rel="preconnect"
                href="https://fonts.gstatic.com"
                crossOrigin="true"
              />
              <link
                href="https://fonts.googleapis.com/css2?family=Oswald:wght@200;300;400;500;600;700&family=Urbanist:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
                rel="stylesheet"
              />
            </Head>
            <Header />
            <ToastContainer />
            <Component {...pageProps} />
            <Footer />
          </Auth>
        ) : (
          <>
            <Head>
              <title>Shoe Store</title>
              <meta name="description" content="Generated by create next app" />
              <meta
                name="viewport"
                content="width=device-width, initial-scale=1"
              />
              <link rel="icon" href="/favicon.ico" />
              <link rel="preconnect" href="https://fonts.googleapis.com" />
              <link
                rel="preconnect"
                href="https://fonts.gstatic.com"
                crossOrigin="true"
              />
              <link
                href="https://fonts.googleapis.com/css2?family=Oswald:wght@200;300;400;500;600;700&family=Urbanist:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
                rel="stylesheet"
              />
            </Head>
            <Header />
            <ToastContainer />
            <Component {...pageProps} />
            <Footer />
          </>
        )}
      </StoreProvider>
    </SessionProvider>
  );
}
